### ISSUE TITLE
Change color of "delete icon" on customizer

### ISSUE THREAD

**Issue by adornista** [adornista/site#21]
![issue-21](https://cloud.githubusercontent.com/assets/22069481/18339586/fc5c616a-75d2-11e6-8f83-f29a2283c6b9.png)

**Comment by asapzulu** [comment]
## Time = 10 mins

Found and replaced SVG image after photoshoping the image with the new brown color.

![screen shot 2016-09-10 at 9 33 00 pm](https://cloud.githubusercontent.com/assets/22117203/18410857/3cef12f0-779e-11e6-8a27-7ed2ea1de031.png)
