### ISSUE TITLE
My account

### ISSUE THREAD

**Issue by adornista** [adornista/site#25]
![issue-26](https://cloud.githubusercontent.com/assets/22069481/18339794/20e73edc-75d4-11e6-921b-5a99c68f749d.png)

**Comment by asapzulu** [comment]
## Time = 60 mins

Fixed, had to re-add in login form code + restyle (design ) code for the form for mobile devices.

Also fixed the "Register" link on the "my account" dropdown icon container to correctly re-direct to the My Account page for register / login.

![screen shot 2016-09-10 at 9 48 39 pm](https://cloud.githubusercontent.com/assets/22117203/18410974/6c1baf96-77a0-11e6-88eb-591db048f8bc.png)
