### ISSUE TITLE
iPad homepage

### ISSUE THREAD

**Issue by adornista** [adornista/site#27]
![issue-28](https://cloud.githubusercontent.com/assets/22069481/18339830/51d4602e-75d4-11e6-91f3-f4b6f3a5f3b2.png)

**Comment by asapzulu** [comment]
## Time = 40 mins

This has been fixed please check and revert.

**Comment by adornista** [comment]
The Tag #adornistas continues to have a line break on iPad

**Comment by asapzulu** [comment]
I've updated the code for this and tested this on my iPad Air + My iPad Mini + iPad Simulator online ( see screen attached ). 
Not sure which iPad version you have, so check again and send me a screenshot with your iPad version or else I can't reproduce the problem. 
![screen shot 2016-09-22 at 11 43 16 am](https://cloud.githubusercontent.com/assets/22117203/18736503/366972a2-80ba-11e6-8038-d1da057dca26.png)

**Comment by adornista** [comment]
It's fixed now
