### ISSUE TITLE
Post sub-titles

### ISSUE THREAD

**Issue by adornista** [adornista/site#29]
![issue-30](https://cloud.githubusercontent.com/assets/22069481/18339854/857277a4-75d4-11e6-9394-c03263a0c092.png)

**Comment by asapzulu** [comment]
**Time = 10 mins**
This has been fixed see attached image. 
![screen shot 2016-09-20 at 12 49 55 pm](https://cloud.githubusercontent.com/assets/22117203/18657875/d9255320-7f30-11e6-81fd-c011c33f6e19.png)
