### ISSUE TITLE
iPhone shop product menu

### ISSUE THREAD

**Issue by adornista** [adornista/site#30]
![issue-31](https://cloud.githubusercontent.com/assets/22069481/18339876/9bb86898-75d4-11e6-87df-d1a227b4007e.png)

**Comment by asapzulu** [comment]
**Time = 50 mins**

Fixed as attached, had to re-design + recode this menu on the product list and single product page. For mobiles + tablets.

![screen shot 2016-09-20 at 7 39 04 pm](https://cloud.githubusercontent.com/assets/22117203/18673725/6e26bc0e-7f7f-11e6-8a5c-8b183b41493b.png)
