### ISSUE TITLE
Payment methods

### ISSUE THREAD

**Issue by adornista** [adornista/site#4]
![issue-4](https://cloud.githubusercontent.com/assets/22069481/18339153/6f34f204-75d0-11e6-8ab0-0895024aca8d.png)

**Comment by adornista** [comment]
## Time = 40 mins

Had to find the appropriate icons, photoshop, size the icons for multiple versions, decided to use bigger icons as its more clear.

![screen shot 2016-09-09 at 10 00 40 am](https://cloud.githubusercontent.com/assets/22069481/18410226/d93e4d98-778e-11e6-94b2-c8fb3f25f18b.png)

**Comment by adornista** [comment]
The WeChat icon needs to be replaced by PAYPAL

**Comment by adornista** [comment]
Take paypal icon

**Comment by asapzulu** [comment]
**Time = 5 mins**
Ok, paypal icon removed.
WeChat added back.
![screen shot 2016-09-24 at 2 58 45 pm](https://cloud.githubusercontent.com/assets/22117203/18806716/6d11edd0-8267-11e6-8098-d2d256c5d76c.png)
