### ISSUE TITLE
Integrating payments & customization

### ISSUE THREAD

**Issue by adornista** [adornista/site#40]
please customise bank transfer to allow QR codes and bank info

**Comment by asapzulu** [comment]
**Time = 180 mins**

It currently looks like this. see attached image.
![screen shot 2016-09-22 at 9 01 38 pm](https://cloud.githubusercontent.com/assets/22117203/18806658/cc026560-8265-11e6-858f-92835a53b932.png)

**Comment by asapzulu** [comment]
The back-end doesn't accept simple wordpress editor, it needs hard coded html which I then output. Initially it was only text ( no ability to style or add the QR code images ), I had to switch it to html on output. 

See image for where its pulled from in the back-end ( DO NOT TOUCH THE CODE or you break the site ).

![screen shot 2016-09-24 at 2 47 24 pm](https://cloud.githubusercontent.com/assets/22117203/18806669/15d549d2-8266-11e6-884d-79cccf25d2c1.png)

**Comment by asapzulu** [comment]
I am waiting for your full bank details to update the content. Please test to make sure that QR codes are still working. If Alipay and WeChat make these QR codes expire then I am sorry the only way will be to manually add people and them tell you the order# on wechat or Alipay which is pretty useless, so you will have no choice but to be official with these payments to avoid dropped orders.

**Comment by adornista** [comment]
I sent you these details by email on Thursday:

Your account name: MOREIRA TAVEIRA DE AMARAL TANIA ISABEL
Your account number: 6214850214557503
Bank Name:  China Merchants Bank （招商银行）
Name of the Branch:  Shanghai Branch, Yanxi Sub-branch （上海分行延西支行）
Address of the Branch:  #555，Fahuazhen Road, Shanghai  （上海市法华镇路555号）

**Comment by adornista** [comment]
I've made the test of the QR-Codes and they work... they go directly to my accounts :)

But there's just an issue with the layout, can you please check?

![screen shot 2016-09-25 at 10 52 26](https://cloud.githubusercontent.com/assets/22069481/18812682/7b69b4d8-830e-11e6-90fa-1965149d623a.png)
![screen shot 2016-09-25 at 10 52 29](https://cloud.githubusercontent.com/assets/22069481/18812683/7de9dc1a-830e-11e6-8486-b80bc2cbe6b7.png)

**Comment by asapzulu** [comment]
**Time = 30 mins**

I've updated the code, I hadn't made it responsive. Please check again.
![screen shot 2016-09-29 at 3 19 34 pm](https://cloud.githubusercontent.com/assets/22117203/18944642/2c6d28da-8659-11e6-9a8a-c3164d1f16f1.png)
![screen shot 2016-09-29 at 3 25 30 pm](https://cloud.githubusercontent.com/assets/22117203/18944648/3823604a-8659-11e6-8135-87aa8c4961b4.png)
![screen shot 2016-09-29 at 3 25 06 pm](https://cloud.githubusercontent.com/assets/22117203/18944675/49c4a872-8659-11e6-882e-61e29d95e3bb.png)
