### ISSUE TITLE
Recommend a friend

### ISSUE THREAD

**Issue by adornista** [adornista/site#41]
![screen shot 2016-09-25 at 09 43 52](https://cloud.githubusercontent.com/assets/22069481/18812431/de8c2f94-8306-11e6-9b91-ce522ab1611d.png)

Can you please align the text to the left, take out the BOLD lettering and add the logo?

**Comment by asapzulu** [comment]
This email will only be seen by us. 
Please delete / close this ticket.

**Comment by adornista** [comment]
But i've tried to recommend the website and this is the only email the system is sending out... I just tried again and i get no email if I recommend the website to myself

**Comment by adornista** [comment]
But i've tried to recommend the website and this is the only email the system is sending out... I just tried again and i get no email if I recommend the website to myself

**Comment by adornista** [comment]
I've added the wrong template but the same is happening to the recommendation.
![197273532](https://cloud.githubusercontent.com/assets/22069481/18946006/9857e764-865f-11e6-9f71-6bc92a2d1492.jpg)
 And i didn't wrote "sunshine" in the email and that comes up :-S And the English in this template is not good or aligned to the left. Could you please correct the wording? "This website" appear twice...

**Comment by adornista** [comment]
BUGS
![screen shot 2016-09-29 at 16 04 55](https://cloud.githubusercontent.com/assets/22069481/18946468/8d227290-8661-11e6-9fc1-8c8675ed487a.png)
![Uploading Screen Shot 2016-09-29 at 16.16.01.png…]()

**Comment by asapzulu** [comment]
**Please close this ticket**

I've tested this form and its working perfectly for me(see attached). Something is wrong with your Safari you seem to be having strange issues. Try with Chrome or Firefox, also make sure you don't copy and paste things into these boxes, obviously its going to give you an error. If it works for me it must work for you.

![screen shot 2016-09-30 at 1 56 24 pm](https://cloud.githubusercontent.com/assets/22117203/18982079/0d9256f2-8716-11e6-8d49-744473b9206a.png)

**Also...there is no sunshine or other fields added to my email**
![screen shot 2016-09-30 at 2 10 24 pm](https://cloud.githubusercontent.com/assets/22117203/18982415/87bb8bcc-8718-11e6-9566-0726ae1ffdd3.png)
