### ISSUE TITLE
Update color on all templates

### ISSUE THREAD

**Issue by adornista** [adornista/site#42]
![screen shot 2016-09-25 at 09 50 10](https://cloud.githubusercontent.com/assets/22069481/18812498/3d44c8be-8309-11e6-802c-a018612f58c7.png)

**Comment by asapzulu** [comment]
**Time = 5 mins**

Done see attached.
![screen shot 2016-09-29 at 2 32 57 pm](https://cloud.githubusercontent.com/assets/22117203/18943368/c343804a-8651-11e6-8640-a2dbb9dfc2c7.png)
