### ISSUE TITLE
[NEW] Redirect adornista.com to beta.adornista.com

### ISSUE THREAD

**Issue by adornista** [adornista/site#43]
Please do this on Oct 7

**Comment by asapzulu** [comment]
#to go into htaccess file 
#Redirect temporarily to beta site:
Redirect 301 / http://beta.adornista.com/

**Comment by asapzulu** [comment]
# Time = 10

**Comment by adornista** [comment]
Let's launch the website and erase beta version.

**Comment by asapzulu** [comment]
This is a big step, I hope we can move it without all the complications to the customizer like last time. I recomend we close most of these bugs first then I move the site.

**Comment by asapzulu** [comment]
Now we need to redirect all links from old 

http://beta.adornista.com to official https://adornista.com 

We need to redirect each corresponding page as the new site has the same structure

in hataccess for example
---------------
RewriteEngine on 
RewriteRule ^(.*)$ http://www.newdomain.com/$1 [R=301,L]

www.example.net/somepage.html?var=foo redirects to www.example.com/somepage.html?var=foo


in hataccess we would put 
---------------
RewriteEngine on 
RewriteRule ^(.*)$ https://adornista.com/$1 [R=301,L]

So new beta.adornista.com....htaccess we would be
------------------

-# Apache config
<FilesMatch ".(eot|ttf|otf|woff)">
	Header set Access-Control-Allow-Origin "*"
</FilesMatch>
 
-# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On


RewriteRule ^(.*)$ https://adornista.com/$1 [R=301,L]


RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

# END WordPress
# php -- BEGIN cPanel-generated handler, do not edit
# This domain inherits the “PHP” package.
# php -- END cPanel-generated handler, do not edit
