### ISSUE TITLE
[NEW] Promotional pop-up

### ISSUE THREAD

**Issue by adornista** [adornista/site#45]
I cannot create a pop-up after several tentatives

**Comment by asapzulu** [comment]
What error did you get ?

**Comment by adornista** [comment]
There's no ERROR... it just doesn't work. I click on the buttons to build the pop-up and nothings happens.

![screen shot 2017-07-27 at 11 38 46](https://user-images.githubusercontent.com/22069481/28666674-4ee95330-72c0-11e7-92b6-d557114a8f81.png)

**Comment by asapzulu** [comment]
Time = 30minutes
================

I had to update the plugin, something had broken down and it wasn't installed properly. Now if you check you should be able to edit the pop-up I've made. I also downloaded some new pop-up template and edited its design to fit what you wanted for the look and feel.
