### ISSUE TITLE
[NEW] Currency change

### ISSUE THREAD

**Issue by adornista** [adornista/site#46]
Please update currency to EURO and delete RMB. There will only be three currencies (GBP, EU, US)

**Comment by asapzulu** [comment]
This required back-end changes with currency converter. Also default site currency settings changed in WooCommerce.

Also needed front-end changes to hide CNY option in switcher (dropdown) incase we need it later on. 

Need to test checkout with new payment methods ( paypal / credit card etc.... )

**Comment by asapzulu** [comment]
**Time = 20 minutes
-----**
