### ISSUE TITLE
[NEW] Payment methods update

### ISSUE THREAD

**Issue by adornista** [adornista/site#48]
Please take out the ALIPAY and WECHAT payments. Update the bank details for BANK TRANSFER. Add new payment method STRIPE or PAYPAL. Let me know what works better for you and i give you the account details.

**Comment by asapzulu** [comment]
I suggest we add both Stripe and PayPal.

Paypal was already there and is by default on all WooCommerce, so updating it is easy just new details.

Stripe has many payments including bitcoin and ApplePay. I can install and configure the plugin for Stripe but it needs us to sign up.

**Comment by asapzulu** [comment]
Paypal I've checked is updated to use your email address.

**Comment by asapzulu** [comment]
I have setup and installed the plugin for Stripe, we need to sign up for the service.. stripe.com I think to finish the setup, see image attached.

Sign up and send me login / account information.
![screen shot 2017-07-03 at 9 03 21 pm](https://user-images.githubusercontent.com/22117203/27794109-5e7e2b8a-6033-11e7-9b64-5d7990d31258.png)

**Comment by asapzulu** [comment]
The newest API allows for Apple Pay and bitcoin but it seems its still very buggy with some reviews of customers getting double charged. The new Stripe is also too new and needs us to upgrade our e-commerce platform ( this may break the entire site ). So I recommend we use the simple stripe for now which I have added to payments. I have also re-organized the payment order so Paypal is on top, bank at the bottom.

**Comment by asapzulu** [comment]
I had to spend alot of time on the stripe API, it seems we can do alot with it down the line, especialy since it has integration with Apple Pay ( I will find a way around it when their WooCommerce is more mature ).

**Comment by asapzulu** [comment]
**Time = 8 hours ( 480 minutes )
=======================**

![screen shot 2017-07-06 at 5 48 07 pm](https://user-images.githubusercontent.com/22117203/27905797-b4c1147a-6273-11e7-8a20-f697c3fa378e.png)

**Comment by adornista** [comment]
Tested - 3 additional comments as below.

COMMENT 1 - I've added an invalid credit card and a weird message comes up. Could you please check?

![screen shot 2017-07-27 at 11 30 36](https://user-images.githubusercontent.com/22069481/28666477-645ffd8c-72bf-11e7-8179-2cd2be68fddd.png)

COMMENT 2 - Please add SWIFT Code TOTAPTPL on BANK TRANSFER and change name to TANIA AMARAL only

![screen shot 2017-07-27 at 11 25 52](https://user-images.githubusercontent.com/22069481/28666526-990d98a0-72bf-11e7-95a6-15380893d9b8.png)

COMMENT 3 - Take out the wechat and alipay logos and add stripe and paypal

![screen shot 2017-07-26 at 23 23 46](https://user-images.githubusercontent.com/22069481/28666548-b22588ca-72bf-11e7-8d29-4a33f92f5e25.png)

**Comment by asapzulu** [comment]
I have updated these. Please test.

**Comment by adornista** [comment]
I've tested a card on STRIPE and it worked! Logos are OK.

**Comment by asapzulu** [comment]
Ok awsome, I am closing this issue for now.
