### ISSUE TITLE
[NEW] Update homepage text regarding shipping

### ISSUE THREAD

**Issue by adornista** [adornista/site#49]
Please update "CHINA ONLY" into "DELIVERING IN EUROPE ONLY" and "FREE SHIPPING" into "FREE SHIPPING OVER €100"
![screen shot 2016-12-12 at 11 42 30](https://cloud.githubusercontent.com/assets/22069481/21087398/65d6c9d2-c060-11e6-9c84-b1effb41a1fd.png)

**Comment by asapzulu** [comment]
TIME = 2 mins
--------------------

Done updated "CHINA ONLY " to:
Europe Delivery
