### ISSUE TITLE
[NEW] Create https encryption

### ISSUE THREAD

**Issue by adornista** [adornista/site#52]
HTTPS encryption enables security, privacy, and prevents censorship.

**Comment by asapzulu** [comment]
Install SSL certificate on the site domain.

**Comment by asapzulu** [comment]
Need to change all urls on the site DB and wordpress from http:  to  https:

Needs to force backend admin to use https: 

Need to add 301 redirect from http: to https

**Comment by asapzulu** [comment]
Configured on site on back-end and front-end for:

beta.adornista.com

**Time=20 minutes
-----** 
![wechatimg54](https://cloud.githubusercontent.com/assets/22117203/26718195/c24ff4ac-47b2-11e7-8131-4cde41c1c989.jpeg)

**Comment by asapzulu** [comment]
Don't forget to do 301 re-direction in htaccess:

![screen shot 2017-06-02 at 5 04 33 pm](https://cloud.githubusercontent.com/assets/22117203/26752184/c97b3744-487c-11e7-9d9f-30d0fe74c348.png)

**Comment by asapzulu** [comment]
Configured on site on back-end and front-end for:

https://adornista.com

Time=5 minutes
-----

**Comment by asapzulu** [comment]
![screen shot 2017-09-02 at 2 50 25 pm](https://user-images.githubusercontent.com/22117203/29993611-b1f97766-8fee-11e7-9caf-646c2b44dcf6.png)
Backend is more secure under https ( SSL installed )

**Comment by asapzulu** [comment]
Front-end of official site is now secure...

**Comment by asapzulu** [comment]
This is the final solution. In HTACCESS add this code to redirect all http to https
================================


# Apache config
<FilesMatch ".(eot|ttf|otf|woff)">
	Header set Access-Control-Allow-Origin "*"
</FilesMatch> 

# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On

    RewriteCond %{SERVER_PORT} !^443$
    RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]

RewriteBase /

RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]

</IfModule>

# END WordPress



=========
Also add this to wp-config.php
===============

define('WP_HOME','https://adornista.com');
define('WP_SITEURL','https://adornista.com');
