### ISSUE TITLE
[NEW] Password Reset Redirect to Login 

### ISSUE THREAD

**Issue by asapzulu** [adornista/site#58]
Make the site more user friendly.
![screen shot 2017-05-25 at 11 44 30 am](https://cloud.githubusercontent.com/assets/22117203/26437626/d0dc90a6-4150-11e7-88fb-aaaa22800d91.png)

After users submit their email on the forgotten password page. 
Show success message for 2 seconds, then redirect to the login page.
The old system stops on the forgotten password page ( a dead end requiring users to manually find the login page ).

**Comment by adornista** [comment]
Tested perfectly.

**Comment by asapzulu** [comment]
Time = 40 minutes
===============
