### ISSUE TITLE
Shop product menu

### ISSUE THREAD

**Issue by adornista** [adornista/site#6]
![issue-6](https://cloud.githubusercontent.com/assets/22069481/18339199/c24b37c8-75d0-11e6-8ab9-2812c5e78341.png)

**Comment by adornista** [comment]
## Time = 20 mins

Had to recode and update the styles, also code updated for the text from the original.

![screen shot 2016-09-10 at 7 54 28 pm](https://cloud.githubusercontent.com/assets/22069481/18410300/ba96fe4c-7790-11e6-942f-4ceae751e980.png)

**Comment by adornista** [comment]
![screen shot 2016-09-22 at 09 56 50](https://cloud.githubusercontent.com/assets/22069481/18734871/fa1e44da-80aa-11e6-8866-347a42adf4a3.png)

**Comment by asapzulu** [comment]
I've updated the code to reflect the correct link. 

Updated old store base link from 
/store/create-design/the-original/
/shop/create-design/the-original/

Test and close.
