### ISSUE TITLE
[NEW] Hubspot forms

### ISSUE THREAD

**Issue by adornista** [adornista/site#61]
I'm getting emails like crazy from Hubspot since I have installed this CRM plugin. I took it out but I still get the messages.. can you check it please?

**Comment by asapzulu** [comment]
**Time == 5 minutes
----------------------** 

OK,

I remember I had added this code in the site theme's footer.php file, and the plugin was activated to make this work. So I'll just remove the code below on the site, I see you de-activated the plugin already. 


<script type="text/javascript" id="hs-script-loader" async defer src="//js.hs-scripts.com/2950497.js"></script>
