### ISSUE TITLE
[NEW] header message

### ISSUE THREAD

**Issue by adornista** [adornista/site#62]
Take 20% discount and add PERSONALISED JACKETS WITH FREE DELIVERY IN PORTUGAL

**Comment by asapzulu** [comment]
Changed to " Free Delivery in Portugal " and have also changed the icon from "%" discount  to a fire / announcement sign. 

![screen shot 2017-08-07 at 12 47 37 pm](https://user-images.githubusercontent.com/22117203/29012513-b601cbe0-7b6e-11e7-92eb-236907f4fbd8.png)


**Time == 10 minutes
-----------------------**
